#!/usr/bin/env python3
"""
Calculate and plot pairwise nucleotide identity from Stockholm alignment files.

This script reads multiple Stockholm (.sto) files generated by cmalign,
calculates the pairwise identity for all sequences within each file, and
generates a boxplot summarizing the identity distributions across different
Rfam families and models.
"""
import argparse
import itertools
import os
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from Bio import AlignIO

# --- Configuration ---
# Define project structure and file locations.
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# Directory containing the alignment files (.sto) generated by run_batch_alignment.py
ALIGNMENT_DIR = PROJECT_ROOT / 'results' / 'alignments'

# Directory containing the original Rfam seed alignments (.stk) for comparison
RFAM_SEED_DIR = PROJECT_ROOT / 'preprocessing' / 'RfamSeed' / 'rfam_out' / 'rfam_stk'

# Output file for the plot
OUTPUT_PLOT_FILE = PROJECT_ROOT / 'results' / 'pairwise_identity_boxplot.png'

# --- Plotting Configuration ---
# Models to process and their desired names in the plot legend
# The order here determines the order of boxes in the plot.
MODELS_TO_PLOT = {
    "nuc-una": "nuc_unaligned",
    "RNAgg-una": "non-nuc_unaligned",
    "nuc-ali": "nuc_aligned",
    "RNAgg-ali": "non-nuc_aligned",
    "seed": "seed",  # Special case for original seed alignment
}

# Define a color palette that matches the example image
PALETTE = {
    "nuc-una": "#8dd3c7",
    "RNAgg-una": "#ffffb3",
    "nuc-ali": "#bebada",
    "RNAgg-ali": "#fb8072",
    "seed": "#80b1d3",
    # "RfamGen" is in the example, but we don't have data for it.
    # If you have it, add it to MODELS_TO_PLOT and here.
}


def calculate_pairwise_identity(alignment):
    """
    Calculates pairwise identity for all sequences in a Bio.Align.MultipleSeqAlignment object.

    Args:
        alignment (MultipleSeqAlignment): An alignment object from Bio.AlignIO.

    Returns:
        list[float]: A list of pairwise identity scores (0.0 to 1.0).
    """
    identities = []
    if len(alignment) < 2:
        return []

    # Create all unique pairs of sequences
    for record1, record2 in itertools.combinations(alignment, 2):
        seq1 = str(record1.seq)
        seq2 = str(record2.seq)

        matches = 0
        # The length of the alignment (number of columns)
        alignment_length = alignment.get_alignment_length()

        if alignment_length == 0:
            continue

        # Count matches, ignoring columns where both sequences have a gap
        valid_columns = 0
        for i in range(alignment_length):
            char1 = seq1[i]
            char2 = seq2[i]

            # Ignore columns where both are gaps
            if char1 in "-." and char2 in "-.":
                continue

            valid_columns += 1
            if char1 == char2 and char1 not in "-.":
                matches += 1

        if valid_columns > 0:
            identity = matches / valid_columns
            identities.append(identity)

    return identities


def main():
    """Main function to run the analysis and plotting workflow."""
    parser = argparse.ArgumentParser(description="Plot pairwise nucleotide identity from alignments.")
    parser.add_argument(
        '--families',
        type=str,
        default=",".join([f"RF{i:05d}" for i in range(1, 11)]),
        help='Comma-separated list of Rfam family IDs to process (e.g., "RF00001,RF00002").'
    )
    args = parser.parse_args()
    families_to_process = sorted([fam.strip() for fam in args.families.split(',')])

    all_data = []

    print("--- Starting Pairwise Identity Calculation ---")

    for family_id in families_to_process:
        print(f"Processing Family: {family_id}")

        for plot_name, model_dir_name in MODELS_TO_PLOT.items():
            file_path = None
            if model_dir_name == "seed":
                # Special case: load original seed alignment
                file_path = RFAM_SEED_DIR / f"{family_id}.stk"
            else:
                # Load generated alignments
                file_path = ALIGNMENT_DIR / model_dir_name / f"{family_id}_aligned.sto"

            if not file_path or not file_path.exists():
                print(f"  [WARNING] File not found for model '{plot_name}', skipping: {file_path}", file=sys.stderr)
                continue

            try:
                # Parse the alignment file (works for both Stockholm)
                alignment = AlignIO.read(file_path, "stockholm")

                # Calculate identities
                identities = calculate_pairwise_identity(alignment)
                if not identities:
                    print(f"  [INFO] No identities calculated for {file_path.name} (sequences < 2).")
                    continue

                # Append data for plotting
                for identity in identities:
                    all_data.append({
                        "family": family_id,
                        "model": plot_name,
                        "identity": identity,
                    })
                print(f"  - Calculated {len(identities)} pairwise identities for '{plot_name}'.")

            except Exception as e:
                print(f"  [ERROR] Failed to process file {file_path.name}: {e}", file=sys.stderr)

    if not all_data:
        print("\n[ERROR] No data was collected. Cannot generate plot. Please check input files and paths.",
              file=sys.stderr)
        sys.exit(1)

    # Create a pandas DataFrame
    df = pd.DataFrame(all_data)

    # --- Plotting ---
    print("\n--- Generating Boxplot ---")
    plt.style.use('seaborn-v0_8-paper')  # Use a style suitable for papers
    fig, ax = plt.subplots(figsize=(15, 6))

    sns.boxplot(
        data=df,
        x="family",
        y="identity",
        hue="model",
        hue_order=list(MODELS_TO_PLOT.keys()),  # Ensure consistent legend order
        palette=PALETTE,
        ax=ax,
        fliersize=0,  # Hide outlier points
        linewidth=1.2,
    )

    # Customize plot aesthetics
    ax.set_xlabel("")
    ax.set_ylabel("Pairwise nucleotide identity", fontsize=14)
    ax.tick_params(axis='x', labelsize=12)
    ax.tick_params(axis='y', labelsize=12)
    ax.set_ylim(0.1, 1.05)

    # Legend
    handles, labels = ax.get_legend_handles_labels()
    ax.legend(handles, labels, title="", loc='upper center', bbox_to_anchor=(0.5, 1.0), ncol=len(labels) // 2)

    plt.tight_layout()

    # Save the plot
    OUTPUT_PLOT_FILE.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(OUTPUT_PLOT_FILE, dpi=300)

    print(f"\n✅ Plot saved successfully to: {OUTPUT_PLOT_FILE}")


if __name__ == "__main__":
    # Check for required packages
    try:
        import pandas
        import seaborn
        import Bio
    except ImportError as e:
        print(f"[ERROR] Missing required Python package: {e.name}", file=sys.stderr)
        print("Please install it by running: pip install pandas seaborn biopython matplotlib", file=sys.stderr)
        sys.exit(1)

    main()
